name: Build NominatimBR Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: tentando logar no docker hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: build da imagem
      run: |
        docker buildx build --push \
          --tag dr2p/nominatimbr:sudeste \
          --platform linux/amd64,linux/arm64 .
