name: Build NominatimBR Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: tentando logar no docker hub
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
    - name: build da imagem amd64
      run: |
        docker buildx build --push --tag dr2p/nominatimbr:amd64 --platform linux/amd64 . && \
        docker buildx build --push --tag dr2p/nominatimbr:arm64 --platform linux/arm64 . && \
        docker manifest create dr2p/nominatimbr:sudeste dr2p/nominatimbr:amd64 dr2p/nominatimbr:arm64 && \
        docker manifest push dr2p/nominatimbr:sudeste

